package(default_visibility = ["//visibility:public"])

cc_library(
    name = "CrashTest",
    srcs = [
        "CrashTest.cpp",
    ],
    deps = [
        "@llvm-project//llvm:Support",
         "@llvm-project//mlir:IR",
         "//crash/dialect:ir"
    ],
)